controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_7
initial:  # Define initial robot poses.
  - group: arm_group
    pose: zero_pose
  - group: hand
    pose: turn_left